version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: acervo-db
    environment:
      POSTGRES_DB: acervo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d acervo"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit:latest
    container_name: acervo-mailpit
    ports:
      - "8025:8025" # Interface web do email
      - "1025:1025" # Porta SMTP
    environment:
      MP_MAX_MESSAGES: 500

  acervo-api:
    build:
      context: ./acervo-api
      dockerfile: Dockerfile
    container_name: acervo-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/acervo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_MAIL_HOST=mailpit
      - SPRING_MAIL_PORT=1025
      - JWT_SECRET=5J8xW9zP2qR4vS6tY7uX1wZ3mK0nL2pQ5aB7cDsEfG9hI1jK3
    depends_on:
      db:
        condition: service_healthy
      mailpit:
        condition: service_started

  acervo-web:
    build:
      context: ./acervo-web
      dockerfile: Dockerfile
    container_name: acervo-web
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8080/api/v1
    depends_on:
      - acervo-api

volumes:
  postgres_data:
